### ISSUE TITLE
Background Image?

### ISSUE THREAD

**Issue by nozpheratu** [willowsystems/jSignature#14]
I saw mention of setting the background colour for the canvas in the source code but didn't see any mention of background image. Does anybody know of a way to essentially stamp an existing image with a signature and export the stamped image as you normally would?

**Comment by dvdotsenko** [comment]
Because of reliance on FlashCanvas for support of IE 8 and older things are complicated.

FlashCanvas does not support "area" transfer for images. It only supports whole-image load, and only in cases where the source image has a `src` attribute that is meaningful to Flash.

Technically nothing stops you from loading an image into the canvas element that jSignature creates. However there is absolutely no way to make it work reliably across major browsers, especially if you take mobile browsers into account.

So, while you can make it work, you cannot make it work **reliably**. For that reason, no official image background API is exposed in jSignature.

If you really want to try to make it work, read the entirety of this thread:
https://groups.google.com/d/topic/flashcanvas/42_3oD4b-wo/discussion

And this post specifically:
https://groups.google.com/d/msg/flashcanvas/42_3oD4b-wo/8-MTd0Juy9gJ

Plan:
1. Initialize jSignature
2. Inject an image into it
3. Make user sign
4. Use jSignature's "image" export format to get it all back, or just use regular canvas API for the same.

**Comment by nozpheratu** [comment]
Thank you for the point in the right direction, I'll update if I ever manage to get anything working.
